Ext.define('FV.store.CaiLMChs', {// 材料名称
    extend: 'Ext.data.Store',

    model: 'FV.model.LabelValue',

    data: [
        {value: 1,   label: '干部履历书'},
        {value: 2,   label: '自传'},
        {value: 3,   label: '履历变化补充报告表'},
        {value: 4,   label: '入团志愿书'},
        {value: 5,   label: '入党志愿书'},
        {value: 6,   label: '入伍（兵役）登记表'},
        {value: 7,   label: '士兵提干报告表'},
        {value: 8,   label: '干部升调报告表'},
        {value: 9,   label: '干部调整级别报告表'},
        {value: 10,   label: '干部任免报告表'},
        {value: 11,   label: '警官任免晋衔报告表'},
        {value: 12,   label: '警官任免晋衔报告表（晋中尉）'},
        {value: 13,   label: '警官任免晋衔报告表（晋上尉）'},
        {value: 14,   label: '警官任免晋衔报告表（晋少校）'},
        {value: 15,   label: '警官任免晋衔报告表（晋中校）'},
        {value: 16,   label: '警官任免晋衔报告表（晋上校）'},
        {value: 17,   label: '警官任免晋衔报告表（晋大校）'},
        {value: 18,   label: '警官任免晋衔报告表（调13级）'},
        {value: 19,   label: '警官任免晋衔报告表（调12级）'},
        {value: 20,   label: '警官任免晋衔报告表（调11级）'},
        {value: 21,   label: '警官任免晋衔报告表（调10级）'},
        {value: 22,   label: '警官任免晋衔报告表（调9级）'},
        {value: 23,   label: '警官任免晋衔报告表（调8级）'},
        {value: 24,   label: '警官任免晋衔报告表（调7级）'},
        {value: 25,   label: '警官任免晋衔报告表（调6级）'},
        {value: 26,   label: '警官任免晋衔报告表（调5级）'},
        {value: 27,   label: '授予军官军衔报告表'},
        {value: 28,   label: '文职干部任免晋级报告表'},
        {value: 29,   label: '专业技术职务评审报告表'},
        {value: 30,   label: '奖励登记报告表'},
        {value: 31,   label: '奖励登记报告表（嘉奖）'},
        {value: 32,   label: '奖励登记报告表（三等功）'},
        {value: 33,   label: '奖励登记报告表（二等功）'},
        {value: 34,   label: '奖励登记报告表（一等功）'},
        {value: 35,   label: '党员登记表'},
        {value: 36,   label: '现役军官薪金审批表'},
        {value: 37,   label: '调整干部薪金审批表'},
        {value: 38,   label: '工资套改审批表'},
        {value: 39,   label: '学历证明'},
        {value: 40,   label: '学员毕（结）业鉴定书'},
        {value: 41,   label: '学习成绩登记表'},
        {value: 42,   label: '入伍时间批注'},
        {value: 43,   label: '干部申请结婚报告表'},
        {value: 44,   label: '干部爱人情况登记表'},
        {value: 45,   label: '家属随军报告表'},
        {value: 46,   label: '证明材料'},
        {value: 47,   label: '鉴定'},
        {value: 48,   label: '干部退休审批报告表'},
        {value: 49,   label: '干部离休审批报告表'},
        {value: 50,   label: '空勤学院登记表'},
        {value: 51,   label: '飞行等级补助报告表'}
	]
});