Ext.define('FV.store.GongZDCs', {// 工资档次
    extend: 'Ext.data.Store',

    model: 'FV.model.LabelValue',

    data: [
        {value: 1 ,   label: '一档'},
        {value: 2 ,   label: '二档'},
        {value: 3 ,   label: '三档'},
        {value: 4 ,   label: '四档'},
        {value: 5 ,   label: '五档'},
        {value: 6 ,   label: '六档'},
        {value: 7 ,   label: '七档'},
        {value: 8 ,   label: '八档'},
        {value: 9 ,   label: '九档'},
        {value: 10,   label: '十档'},
        {value: 11,   label: '十一档'},
        {value: 12,   label: '十二档'},
        {value: 13,   label: '十三档'},
        {value: 14,   label: '十四档'},
        {value: 15,   label: '十五档'},
        {value: 16,   label: '十六档'},
        {value: 17,   label: '十七档'},
        {value: 18,   label: '十八档'},
        {value: 19,   label: '十九档'},
        {value: 20,   label: '二十档'},
        {value: 21,   label: '二一档'},
        {value: 22,   label: '二二档'},
        {value: 23,   label: '二三档'},
        {value: 24,   label: '二四档'},
        {value: 25,   label: '二五档'},
        {value: 26,   label: '二六档'},
        {value: 27,   label: '二七档'},
        {value: 28,   label: '二八档'},
        {value: 29,   label: '二九档'},
        {value: 30,   label: '三十档'},
        {value: 31,   label: '三一档'},
        {value: 32,   label: '三二档'},
        {value: 33,   label: '三三档'},
        {value: 34,   label: '三四档'},
        {value: 35,   label: '三五档'},
        {value: 36,   label: '三六档'},
        {value: 37,   label: '三七档'},
        {value: 38,   label: '三八档'},
        {value: 39,   label: '三九档'},
        {value: 40,   label: '四十档'}
	]
});
