Ext.define('FV.store.JiShZhWs', {// 技术职务 职务资格  两位数字： 第一位是技术系列，第二位是对应技术职务等级
    extend: 'Ext.data.Store',

    model: 'FV.model.LabelValue',

    data: [
        {value: 12,   label: '工程系列-高级工程师'},
        {value: 13,   label: '工程系列-工程师'},
        {value: 14,   label: '工程系列-助理工程师'},
        {value: 15,   label: '工程系列-技术员'},
        {value: 21,   label: '医学系列-主任医师'},
        {value: 22,   label: '医学系列-副主任医师'},
        {value: 23,   label: '医学系列-主治医师'},
        {value: 24,   label: '医学系列-医师'},
        {value: 25,   label: '医学系列-医士'},
        {value: 31,   label: '护理学系列-主任护师'},
        {value: 32,   label: '护理学系列-副主任护师'},
        {value: 33,   label: '护理学系列-主管护师'},
        {value: 34,   label: '护理学系列-护师'},
        {value: 35,   label: '护理学系列-护士'},
        {value: 42,   label: '会计系列-高级会计师'},
        {value: 43,   label: '会计系列-会计师'},
        {value: 44,   label: '会计系列-助理会计师'},
        {value: 45,   label: '会计系列-会计员'},
        {value: 52,   label: '审计系列-高级审计师'},
        {value: 53,   label: '审计系列-审计师'},
        {value: 54,   label: '审计系列-助理审计师'},
        {value: 55,   label: '审计系列-审计员'},
        {value: 61,   label: '记者系列-高级记者'},
        {value: 62,   label: '记者系列-主任记者'},
        {value: 63,   label: '记者系列-记者'},
        {value: 64,   label: '记者系列-助理记者'},
        {value: 71,   label: '编辑系列-高级编辑'},
        {value: 72,   label: '编辑系列-主任编辑'},
        {value: 73,   label: '编辑系列-编辑'},
        {value: 74,   label: '编辑系列-助理编辑'},
        {value: 83,   label: '出版系列-一级校对'},
        {value: 84,   label: '出版系列-二级校对'},
        {value: 85,   label: '出版系列-三级校对'},
        {value: 91,   label: '教育系列-教授'},
        {value: 92,   label: '教育系列-副教授'},
        {value: 93,   label: '教育系列-讲师'},
        {value: 94,   label: '教育系列-助教'},
        {value: 0,   label: '无技术职务'}
	]
});
