Ext.define('FV.store.XueWs', {// 学位
    extend: 'Ext.data.Store',

    model: 'FV.model.LabelValue',

    data: [
        {value: null,   label: '请选择...'},
        {value: 200,   label: '博士'},
        {value: 201,   label: '哲学博士'},
        {value: 202,   label: '经济学博士'},
        {value: 203,   label: '法学博士'},
        {value: 204,   label: '教育学博士'},
        {value: 205,   label: '文学博士'},
        {value: 206,   label: '历史学博士'},
        {value: 207,   label: '理学博士'},
        {value: 208,   label: '工学博士'},
        {value: 209,   label: '农学博士'},
        {value: 210,   label: '医学博士'},
        {value: 211,   label: '军事学博士'},
        {value: 300,   label: '硕士'},
        {value: 301,   label: '哲学硕士'},
        {value: 302,   label: '经济学硕士'},
        {value: 303,   label: '法学硕士'},
        {value: 304,   label: '教育学硕士'},
        {value: 305,   label: '文学硕士'},
        {value: 306,   label: '历史学硕士'},
        {value: 307,   label: '理学硕士'},
        {value: 308,   label: '工学硕士'},
        {value: 309,   label: '农学硕士'},
        {value: 310,   label: '医学硕士'},
        {value: 311,   label: '军事学硕士'},
        {value: 400,   label: '学士'},
        {value: 401,   label: '哲学学士'},
        {value: 402,   label: '经济学学士'},
        {value: 403,   label: '法学学士'},
        {value: 404,   label: '教育学学士'},
        {value: 405,   label: '文学学士'},
        {value: 406,   label: '历史学学士'},
        {value: 407,   label: '理学学士'},
        {value: 408,   label: '工学学士'},
        {value: 409,   label: '农学学士'},
        {value: 410,   label: '医学学士'},
        {value: 411,   label: '军事学学士'},
        {value: 100,   label: '名誉博士'},
        {value: 0,   label: '无学位'}
	]
});
